name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

# Disable previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# ${{ vars.CI_UNIFIED_IMAGE }} is defined in the repository variables

jobs:
  fmt:
    name: Cargo fmt
    runs-on: ubuntu-latest
    container:
      image: ${{ vars.CI_IMAGE }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Rust nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt

      - name: Rust Cache
        uses: Swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84 # v2.7.3
        with:
          cache-on-failure: true
          cache-all-crates: true

      - name: Cargo fmt
        run: cargo fmt --all -- --check

      - if: "failure()"
        uses: "andymckay/cancel-action@271cfbfa11ca9222f7be99a47e8f929574549e0a" # v0.4

  machete:
    name: Check unused dependencies
    runs-on: ubuntu-latest
    container:
      image: ${{ vars.CI_IMAGE }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Rust Cache
        uses: Swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84 # v2.7.3
        with:
          cache-on-failure: true
          cache-all-crates: true

      - name: Install cargo-machete
        run: cargo install cargo-machete

      - name: Check unused dependencies 
        run: cargo machete

      - if: "failure()"
        uses: "andymckay/cancel-action@271cfbfa11ca9222f7be99a47e8f929574549e0a" # v0.4

  check:
    name: Cargo check
    runs-on: ubuntu-latest
    container:
      image: ${{ vars.CI_IMAGE }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Rust Cache
        uses: Swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84 # v2.7.3
        with:
          cache-on-failure: true
          cache-all-crates: true

      - name: Cargo check
        run: cargo check

      - if: "failure()"
        uses: "andymckay/cancel-action@271cfbfa11ca9222f7be99a47e8f929574549e0a" # v0.4

  doc:
    name: Check documentation
    runs-on: ubuntu-latest
    container:
      image: ${{ vars.CI_IMAGE }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Rust Cache
        uses: Swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84 # v2.7.3
        with:
          cache-on-failure: true
          cache-all-crates: true
      - name: Check documentation
        run: RUSTDOCFLAGS="-D warnings -D rustdoc::broken_intra_doc_links" cargo doc --workspace --no-deps --document-private-items

      - if: "failure()"
        uses: "andymckay/cancel-action@271cfbfa11ca9222f7be99a47e8f929574549e0a" # v0.4

  clippy:
    name: Cargo clippy
    runs-on: ubuntu-latest
    container:
      image: ${{ vars.CI_IMAGE }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Rust Cache
        uses: Swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84 # v2.7.3
        with:
          cache-on-failure: true
          cache-all-crates: true

      - name: Run clippy
        run: cargo clippy

      - if: "failure()"
        uses: "andymckay/cancel-action@271cfbfa11ca9222f7be99a47e8f929574549e0a" # v0.4

  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    container:
      image: ${{ vars.CI_IMAGE }}
      options: --sysctl net.ipv6.conf.all.disable_ipv6=0
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Rust Cache
        uses: Swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84 # v2.7.3
        with:
          cache-on-failure: true
          cache-all-crates: true

      - name: Run tests
        run: cargo test

      - if: "failure()"
        uses: "andymckay/cancel-action@271cfbfa11ca9222f7be99a47e8f929574549e0a" # v0.4
